footprint: [[0.30, 0.30], [-0.30, 0.30], [-0.30, -0.30], [0.30, -0.30]]
inflation_radius: 0.25

#Obstacle marking parameters
obstacle_range: 2.0
max_obstacle_height: 0.63
min_obstacle_height: 0.0
raytrace_range: 4.0

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 10} 
