controller_frequency: 10.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

DWAPlannerROS:
   acc_lim_x: 1.0
   acc_lim_y: 0.0
   acc_lim_th: 0.3
   max_trans_vel: 2.0
   min_trans_vel: 0.5
   max_vel_x: 2.0
   min_vel_x: 0.5
   max_vel_y: 0.0
   min_vel_y: 0.0
   max_rot_vel: 0.3
   min_rot_vel: -0.3
   

   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.05  # 5 cm
   latch_xy_goal_tolerance: false

   sim_time: 1.0
   sim_granularity: 0.025
   vx_samples: 10
   vy_samples: 10
   vtheta_samples: 70
   controller_frequency: 1.5
   penalize_negative_x: false

   path_distance_bias: 32.0
   goal_distance_bias: 24.0
   occdist_scale: 24.0
   forward_point_distance: 0.50
   stop_time_buffer: 0.2
   scaling_speed: 0.25
   max_scaling_factor: 0.2 
   
   oscillation_reset_dist: 0.05
   
   prune_plan: false
